Update Postman.yml

diff --git a/.github/workflows/Postman.yml b/.github/workflows/Postman.yml
--- a/.github/workflows/Postman.yml
+++ b/.github/workflows/Postman.yml
@@ -9,7 +9,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Login to Postman CLI
         run: |
-          postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }} || { echo "Login failed"; exit 1; }
+          postman login --with-api-key ${{ secrets.POSTMAN_API_LOGIN_KEY }} || { echo "Login failed"; exit 1; }
 
       - name: Login to Postman CLI
         run: |
